# Generated by Django 4.2.6 on 2023-12-25 14:27

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='Unnamed', max_length=50, null=True, verbose_name='имя')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('avatar', models.ImageField(null=True, upload_to='img/avatars/', verbose_name='аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='заголовок')),
                ('starting_bid', models.FloatField(verbose_name='начальная ставка')),
                ('active', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 27, 17, 45619), verbose_name='дата начала аукциона')),
                ('datetime_finish', models.DateTimeField(verbose_name='дата окончания аукциона')),
            ],
            options={
                'verbose_name': 'Аукцион',
                'verbose_name_plural': 'Аукционы',
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], max_length=20, verbose_name='статус')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
                ('token', models.CharField(max_length=200, verbose_name='токен')),
                ('like', models.IntegerField(default=0, verbose_name='лайк')),
                ('image', models.ImageField(upload_to='apps/main/static/img/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'нфт',
                'verbose_name_plural': 'нфт',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='НФТ_в_транзакции', to='main.nft', verbose_name='НФТ')),
                ('user_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='покупатель_в_транзакции', to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
                ('user_saler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='продавец_в_транзакции', to=settings.AUTH_USER_MODEL, verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
        migrations.CreateModel(
            name='NftCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('datetime_created', models.DateField(verbose_name='дата')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='коллекция', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'коллекция',
                'verbose_name_plural': 'коллекции',
            },
        ),
        migrations.AddField(
            model_name='nft',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='нфт', to='main.nftcollection', verbose_name='Коллекция'),
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='нфт_коммент', to='main.nft', verbose_name='нфт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='комментарий_автор', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 27, 17, 45619), verbose_name='дата создания')),
                ('last_hash', models.CharField(max_length=200, null=True, verbose_name='предыдущий хэш')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='транзакция', to='main.transaction', verbose_name='инфа')),
            ],
            options={
                'verbose_name': 'блок',
                'verbose_name_plural': 'блокчейн',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='деньги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ставка_на_аукцион', to='main.auction', verbose_name='аукицон')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ставка', to=settings.AUTH_USER_MODEL, verbose_name='юзер')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nft', verbose_name='нфт_на_аукционе'),
        ),
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='аукцион_владелец', to=settings.AUTH_USER_MODEL, verbose_name='владелец_аукциона'),
        ),
    ]
