# Generated by Django 4.2.6 on 2023-12-25 14:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 50, 3, 671560), verbose_name='дата начала аукциона'),
        ),
        migrations.AlterField(
            model_name='block',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 20, 50, 3, 670547), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='nftcollection',
            name='datetime_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
    ]
