# Generated by Django 4.2.6 on 2023-12-25 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_auction_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 21, 46, 55, 934824), verbose_name='дата начала аукциона'),
        ),
        migrations.AlterField(
            model_name='block',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 21, 46, 55, 934824), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='apps/main/static/img/avatars/no_ava.png', upload_to='img/avatars/', verbose_name='аватар'),
        ),
    ]
