# Generated by Django 4.2.6 on 2023-12-26 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_auction_datetime_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='description',
            field=models.CharField(default='Cool NFT', max_length=250, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 10, 30, 53, 814418), verbose_name='дата начала аукциона'),
        ),
        migrations.AlterField(
            model_name='block',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 10, 30, 53, 813418), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/no_ava.png', upload_to='avatars/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='Active', max_length=20, verbose_name='статус'),
        ),
    ]
